services:
  streamlit:
    container_name: "web_streamlit"
    build:
      dockerfile: docker/Dockerfile
      context: ./
    restart: always
    ports:
      - '8501:8501'
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=venda
    ports:
      - '5432:5432'
    volumes:
      - ./venda_data:/var/lib/venda/data