services:
  streamlit:
    container_name: "web_streamlit"
    build:
      dockerfile: docker/Dockerfile
      context: ./
    restart: always
    ports:
      - '8501:8501'
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=venda
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=venda
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

# Seção para declarar o volume
volumes:
  pgdata:
